#!/usr/bin/python2.6

import sys

from PySide import QtCore
from PySide import QtGui
from PySide import QtDeclarative
import os

# Comment the line below if you don't want to use OpenGL for QML rendering or if it is not supported
from PySide import QtOpenGL

import gconf

import dbus
import dbus.mainloop.glib

from subprocess import call

class Bridge(QtCore.QObject):
	def __init__(self):
		QtCore.QObject.__init__(self)
                self._settings = QtCore.QSettings()
		self._lat = self._long = 0
		self._zoom = 8
		self._token = ''
		self._minDistance = 100
		self._minTime = 15
		self._minAccuracy = 100
		self._enabled = True
		self._autoCentre = True
		self._autoZoom = True
		self._screenOn = True
		self._dest = ''
                self._dests = ''
		self._easyRead = False
		self.latChanged.connect(self.saveLat)
		self.longChanged.connect(self.saveLong)
		self.zoomChanged.connect(self.saveZoom)
		self.tokenChanged.connect(self.saveToken)
		self.minDistanceChanged.connect(self.saveMinDistance)
		self.minTimeChanged.connect(self.saveMinTime)
		self.minAccuracyChanged.connect(self.saveMinAccuracy)
		self.enabledChanged.connect(self.saveEnabled)
		self.autoCentreChanged.connect(self.saveAutoCentre)
		self.autoZoomChanged.connect(self.saveAutoZoom)
		self.screenOnChanged.connect(self.saveScreenOn)
		self.easyReadChanged.connect(self.saveEasyRead)
                self.destsChanged.connect(self.saveDests)

	@QtCore.Slot()
	def openSettings(self):
		# = 'com..'
		#path = '/'
		#interface = 'com.nokia.DuiControlPanelIf'
		##method = 'appletPage'
		## Get the session bus
		#bus = dbus.SessionBus()
		#proxy = bus.get_object(service, path)
		#connection = dbus.Interface(proxy, interface)
		#connection.appletPage('GAuth')
		call(['dbus-send','--session','--dest=com.nokia.DuiControlPanel','--print-reply','/','com.nokia.DuiControlPanelIf.appletPage',"string:GETA"])

	@QtCore.Slot()
	def readConfig(self):
		prefix = '/apps/ControlPanel/PyGETA/'
		self.lat = gconf.client_get_default().get_float(prefix+'View/Latitude') or 0
		self.long = gconf.client_get_default().get_float(prefix+'View/Longitude') or 0
		self.zoom = gconf.client_get_default().get_int(prefix+'View/Zoom') or 8
		self.token = gconf.client_get_default().get_string(prefix+'Latitude/Token') or str()
		self.minDistance = gconf.client_get_default().get_int(prefix+'Latitude/MinDistance') or 100
		self.minTime = gconf.client_get_default().get_int(prefix+'Latitude/MinTime') or 15
		self.minAccuracy = gconf.client_get_default().get_int(prefix+'Latitude/MinAccuracy') or 100
		value = gconf.client_get_default().get_bool(prefix+'Latitude/Enabled')
		if (value is None):
			value = True
		self.enabled = value
		value = gconf.client_get_default().get_bool(prefix+'View/AutoCentre')
		if (value is None):
			value = True
		self.autoCentre = value
		value = gconf.client_get_default().get_bool(prefix+'View/AutoZoom')
		if (value is None):
			value = True
		self.autoZoom = value
		value = gconf.client_get_default().get_bool(prefix+'View/ScreenOn')
		if (value is None):
			value = False
		self.screenOn = value
		value = gconf.client_get_default().get_bool(prefix+'View/EasyRead')
		if (value is None):
			value = False
		self.easyRead = value
                self.dests = gconf.client_get_default().get_string(prefix+'View/Recents') or str()

	def _get_dests(self):
		return self._dests

	def _set_dests(self, dests):
		if (dests != self._dests):
			self._dests = dests
			self.destsChanged.emit()

	def _get_lat(self):
		return self._lat

	def _set_lat(self, lat):
		if (lat != self._lat):
			self._lat = lat
			self.latChanged.emit()

	def _get_long(self):
		return self._long

	def _set_long(self, lng):
		if (lng != self._long):
			self._long = lng
			self.longChanged.emit()

	def _get_zoom(self):
		return self._zoom

	def _set_zoom(self, zoom):
		if (zoom != self._zoom):
			self._zoom = zoom
			self.zoomChanged.emit()

	def _get_token(self):
		return self._token

	def _set_token(self, token):
		if (token != self._token):
			self._token = token
			self.tokenChanged.emit()

	def _get_minDistance(self):
		return self._minDistance

	def _set_minDistance(self, value):
		if (value != self._minDistance):
			self._minDistance = value
			self.minDistanceChanged.emit()

	def _get_minTime(self):
		return self._minTime

	def _set_minTime(self, value):
		if (value != self._minTime):
			self._minTime = value
			self.minTimeChanged.emit()

	def _get_minAccuracy(self):
		return self._minAccuracy

	def _set_minAccuracy(self, value):
		if (value != self._minAccuracy):
			self._minAccuracy = value
			self.minAccuracyChanged.emit()

	def _get_enabled(self):
		return self._enabled

	def _set_enabled(self, value):
		if (value != self._enabled):
			self._enabled = value
			self.enabledChanged.emit()

	def _get_autoCentre(self):
		return self._autoCentre

	def _set_autoCentre(self, value):
		if (value != self._autoCentre):
			self._autoCentre = value
			self.autoCentreChanged.emit()

	def _get_autoZoom(self):
		return self._autoZoom

	def _set_autoZoom(self, value):
		if (value != self._autoZoom):
			self._autoZoom = value
			self.autoZoomChanged.emit()

	def _get_screenOn(self):
		return self._screenOn

	def _set_screenOn(self, value):
		if (value != self._screenOn):
			self._screenOn = value
			self.screenOnChanged.emit()

	def _get_easyRead(self):
		return self._easyRead

	def _set_easyRead(self, value):
		if (value != self._easyRead):
			self._easyRead = value
			self.easyReadChanged.emit()

     	def _get_dest(self):
		return str(self._settings.value("Destination"))

 	def _set_dest(self, value):
		if (value != self.dest):
			self._settings.setValue("Destination", value)
			self.destChanged.emit()

	destsChanged = QtCore.Signal()
	latChanged = QtCore.Signal()
	longChanged = QtCore.Signal()
	zoomChanged = QtCore.Signal()
	tokenChanged = QtCore.Signal()
	minDistanceChanged = QtCore.Signal()
	minTimeChanged = QtCore.Signal()
	minAccuracyChanged = QtCore.Signal()
	enabledChanged = QtCore.Signal()
	autoCentreChanged = QtCore.Signal()
	autoZoomChanged = QtCore.Signal()
	easyReadChanged = QtCore.Signal()
	screenOnChanged = QtCore.Signal()
        destChanged = QtCore.Signal()

	@QtCore.Slot()
	def saveDests(self):
		gconf.client_get_default().set_string('/apps/ControlPanel/PyGETA/View/Recents', self._dests)

	@QtCore.Slot()
	def saveLat(self):
		gconf.client_get_default().set_float('/apps/ControlPanel/PyGETA/View/Latitude', self._lat)

	@QtCore.Slot()
	def saveLong(self):
		gconf.client_get_default().set_float('/apps/ControlPanel/PyGETA/View/Longitude', self._long)

	@QtCore.Slot()
	def saveZoom(self):
		gconf.client_get_default().set_int('/apps/ControlPanel/PyGETA/View/Zoom', self._zoom)

	@QtCore.Slot()
	def saveToken(self):
		gconf.client_get_default().set_string('/apps/ControlPanel/PyGETA/Latitude/Token', self._token)

	@QtCore.Slot()
	def saveMinDistance(self):
		gconf.client_get_default().set_int('/apps/ControlPanel/PyGETA/Latitude/MinDistance', self._minDistance)

	@QtCore.Slot()
	def saveMinTime(self):
		gconf.client_get_default().set_int('/apps/ControlPanel/PyGETA/Latitude/MonTime', self._minTime)

	@QtCore.Slot()
	def saveMinAccuracy(self):
		gconf.client_get_default().set_string('/apps/ControlPanel/PyGETA/Latitude/MinAccuracy', self._minAccuracy)

	@QtCore.Slot()
	def saveEnabled(self):
		gconf.client_get_default().set_bool('/apps/ControlPanel/PyGETA/Latitude/Enabled', self._enabled)

	@QtCore.Slot()
	def saveAutoCentre(self):
		gconf.client_get_default().set_bool('/apps/ControlPanel/PyGETA/View/AutoCentre', self._autoCentre)

	@QtCore.Slot()
	def saveAutoZoom(self):
		gconf.client_get_default().set_bool('/apps/ControlPanel/PyGETA/View/AutoZoom', self._autoZoom)

	@QtCore.Slot()
	def saveScreenOn(self):
		gconf.client_get_default().set_bool('/apps/ControlPanel/PyGETA/View/ScreenOn', self._screenOn)

	@QtCore.Slot()
	def saveEasyRead(self):
		gconf.client_get_default().set_bool('/apps/ControlPanel/PyGETA/View/EasyRead', self._easyRead)

	dests = QtCore.Property(str, _get_dests, _set_dests, notify=destsChanged)
	lat = QtCore.Property(float, _get_lat, _set_lat, notify=latChanged)
	long = QtCore.Property(float, _get_long, _set_long, notify=longChanged)
	zoom = QtCore.Property(int, _get_zoom, _set_zoom, notify=zoomChanged)
	token = QtCore.Property(str, _get_token, _set_token, notify=tokenChanged)
	minDistance = QtCore.Property(int, _get_minDistance, _set_minDistance, notify=minDistanceChanged)
	minTime = QtCore.Property(int, _get_minTime, _set_minTime, notify=minTimeChanged)
	minAccuracy = QtCore.Property(int, _get_minAccuracy, _set_minAccuracy, notify=minAccuracyChanged)
	enabled = QtCore.Property(bool, _get_enabled, _set_enabled, notify=enabledChanged)
	autoCentre = QtCore.Property(bool, _get_autoCentre, _set_autoCentre, notify=autoCentreChanged)
	autoZoom = QtCore.Property(bool, _get_autoZoom, _set_autoZoom, notify=autoZoomChanged)
	screenOn = QtCore.Property(bool, _get_screenOn, _set_screenOn, notify=screenOnChanged)
	easyRead = QtCore.Property(bool, _get_easyRead, _set_easyRead, notify=easyReadChanged)
        dest = QtCore.Property(str, _get_dest, _set_dest, notify=destChanged)

def main():

    # Enable glib main loop support
    dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

    app = QtGui.QApplication(sys.argv)
    QtCore.QCoreApplication.setOrganizationName("Techtransit")
    QtCore.QCoreApplication.setOrganizationDomain("techtransit.blogspot.com")
    QtCore.QCoreApplication.setApplicationName("GETA")
    view = QtDeclarative.QDeclarativeView()

    # Comment the two lines below if you don't want to use OpenGL for QML rendering or if it is not supported
    glw = QtOpenGL.QGLWidget()
    view.setViewport(glw)

    b = Bridge()

    view.rootContext().setContextProperty('bridge', b)

    if os.path.exists(os.path.join('qml', 'main.qml')):
        view.setSource(os.path.join('qml','main.qml'))
    else:
        view.setSource('/opt/pygeta/qml/main.qml')

    view.showFullScreen()
    sys.exit(app.exec_())

if __name__ == "__main__":
    main()
